name: my-badges

on:
  workflow_dispatch:
  schedule:
    - cron: '13 9 * * 1-5'    # 09:13 UTC
    - cron: '47 10 * * 1-5'   # 10:47 UTC
    - cron: '36 12 * * 1-5'   # 12:36 UTC
    - cron: '58 14 * * 0-5'   # 14:58 UTC
    - cron: '24 17 * * 1-6'   # 17:24 UTC

permissions:
  contents: write

jobs:
  my-badges:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Configure Git User
        run: |
          git config --global user.name "Nengock"
          git config --global user.email "Nengock@users.noreply.github.com"

      - name: Update My Badges
        run: npx update-my-badges ${{github.repository_owner}}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Commit and Push Changes
        run: |
          git add .
          git commit -m "Update badges"
          git pull --rebase
          git push
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Update My Quote
        uses: siddharth2016/quote-readme@main
