name: my-badges

on:
  workflow_dispatch:
  schedule:
    - cron: '0 0 * * *'

permissions:
  contents: write

jobs:
  my-badges:
    runs-on: ubuntu-latest
    steps:
      - name: Configure Git
        run: 
          git config  user.email "nengock@yahoo.com"
          git config  user.name "Wayan P."
      - name: Update My Badges
        run: npx update-my-badges ${{github.repository_owner}}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          GITHUB_USER: Nengock
      - name: Update My Quote
        uses: siddharth2016/quote-readme@main
